facebook:
  client:
    clientId: 1750625705154428
    clientSecret: 3ff875a122647671398f16b532d51ec2
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri:  https://graph.facebook.com/me